services:
  - type: web
    name: my-node-backend
    env: node
    plan: free
    branch: main
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  # Optional, Render auto-assigns PORT
      - key: MONGO_URI
